In [1]:
import pandas as pd

df1 = pd.read_csv('Appointments.csv')
df2 = pd.read_csv('Appointments(1).csv')
df3 = pd.read_csv('Appointments(2).csv')
df4 = pd.read_csv('Appointments(3).csv')
df5 = pd.read_csv('Appointments(4).csv')
df6 = pd.read_csv('Appointments(5).csv')
df7 = pd.read_csv('Appointments(6).csv')

df = pd.concat([df1,df2,df3,df4,df5,df6,df7], ignore_index=True)
# Step 1: collapse truly identical rows (same as before)
df = df.drop_duplicates(subset=['Appointment Date', 'Booked Date', 'Invoice No', 'Guest Name',
       'Service Name', 'Center Name', 'Start Time', 'End Time',
       'Scheduled Service Duration', 'Scheduled Service and Recovery Duration',
       'Recovery Time', 'Stylist', 'Status'])

# Step 2: resolve status conflicts — Deleted beats Closed beats Checkin
status_priority = {'Checkin': 0, 'Closed': 1, 'Deleted': 2}
df['_sp'] = df['Status'].map(status_priority).fillna(0)
df = (df.sort_values('_sp')
        .drop_duplicates(subset=['Invoice No', 'Service Name'], keep='last')
        .drop(columns='_sp'))

df["Appointment Date"] = pd.to_datetime(df["Appointment Date"])
df["Booked Date"] = pd.to_datetime(df["Booked Date"])
df = df.sort_values("Appointment Date")

df

,Appointment Date,Booked Date,Invoice No,Guest Name,Service Name,Center Name,Start Time,End Time,Scheduled Service Duration,Scheduled Service and Recovery Duration,Recovery Time,Stylist,Room,Status,Queue appointment type
101422,2021-04-02,2021-04-01,II52134753,LILIA HERNANDEZ,upper lip,Unique Threading,4/2/2021 01:08 PM,4/2/2021 01:08 PM,0:00,0:00,0:00,GANGA GIRI,NaN,Closed,NaN
101420,2021-04-02,2021-04-01,II52134773,CHRYSTA BRAKE,Eyebrows,Unique Threading,4/2/2021 05:46 PM,4/2/2021 05:46 PM,0:00,0:00,0:00,KOPILA BANIYA,NaN,Closed,NaN
101419,2021-04-02,2021-04-01,II52134756,TARA CHATHA,Eyebrows,Unique Threading,4/2/2021 12:51 PM,4/2/2021 12:51 PM,0:00,0:00,0:00,KOPILA BANIYA,NaN,Closed,NaN
101418,2021-04-02,2021-04-01,II52134747,EARLEAN DOBSON,Brazilian Wax,Unique Threading,4/2/2021 12:02 PM,4/2/2021 12:02 PM,0:00,0:00,0:00,GANGA GIRI,NaN,Closed,NaN
101417,2021-04-02,2021-04-01,II52134745,Cavanna Liggens,Eyebrows,Unique Threading,4/2/2021 11:35 AM,4/2/2021 11:35 AM,0:00,0:00,0:00,KOPILA BANIYA,NaN,Closed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,2026-06-01,2026-06-01,UT-R-38912,Ana Wong,Eyebrows,Unique Threading,6/1/2026 10:15 AM,6/1/2026 10:25 AM,0:10,0:10,0:00,Manu Ghimire,NaN,Closed,Add to queue
1,2026-06-01,2026-06-01,UT-R-38913,Britney carrasco,Eyebrows,Unique Threading,6/1/2026 10:45 AM,6/1/2026 10:55 AM,0:10,0:10,0:00,Mina Pandey,NaN,Closed,Add to queue
12,2026-06-01,2026-06-01,UT-R-38919,Melissa Rojas,Nose outside,Unique Threading,6/1/2026 02:35 PM,6/1/2026 02:40 PM,0:05,0:05,0:00,KOPILA BANIYA,NaN,Closed,Add to queue
11,2026-06-01,2026-06-01,UT-R-38919,Melissa Rojas,Eyebrows,Unique Threading,6/1/2026 02:20 PM,6/1/2026 02:30 PM,0:10,0:10,0:00,KOPILA BANIYA,NaN,Closed,Add to queue
18,2026-06-01,2026-06-01,UT-R-38922,KATY BROOKS,Eyebrows,Unique Threading,6/1/2026 03:15 PM,6/1/2026 03:25 PM,0:10,0:10,0:00,Mina Pandey,NaN,Closed,Add to queue

In [2]:
df['Guest Name'] = df["Guest Name"].str.strip().str.title()
df = df[df["Status"] == "Closed"]
df = df[df["Guest Name"] != "Online Guest"]
print(df.shape)
print(df["Guest Name"].nunique())
print(df["Appointment Date"].min())
print(df["Appointment Date"].max())

(90834, 15)
7989
2021-04-02 00:00:00
2026-06-01 00:00:00

In [3]:
df.to_csv("appointments_clean.csv", index=False)
df = pd.read_csv("appointments_clean.csv")
df

,Appointment Date,Booked Date,Invoice No,Guest Name,Service Name,Center Name,Start Time,End Time,Scheduled Service Duration,Scheduled Service and Recovery Duration,Recovery Time,Stylist,Room,Status,Queue appointment type
0,2021-04-02,2021-04-01,II52134753,Lilia Hernandez,upper lip,Unique Threading,4/2/2021 01:08 PM,4/2/2021 01:08 PM,0:00,0:00,0:00,GANGA GIRI,NaN,Closed,NaN
1,2021-04-02,2021-04-01,II52134773,Chrysta Brake,Eyebrows,Unique Threading,4/2/2021 05:46 PM,4/2/2021 05:46 PM,0:00,0:00,0:00,KOPILA BANIYA,NaN,Closed,NaN
2,2021-04-02,2021-04-01,II52134756,Tara Chatha,Eyebrows,Unique Threading,4/2/2021 12:51 PM,4/2/2021 12:51 PM,0:00,0:00,0:00,KOPILA BANIYA,NaN,Closed,NaN
3,2021-04-02,2021-04-01,II52134747,Earlean Dobson,Brazilian Wax,Unique Threading,4/2/2021 12:02 PM,4/2/2021 12:02 PM,0:00,0:00,0:00,GANGA GIRI,NaN,Closed,NaN
4,2021-04-02,2021-04-01,II52134745,Cavanna Liggens,Eyebrows,Unique Threading,4/2/2021 11:35 AM,4/2/2021 11:35 AM,0:00,0:00,0:00,KOPILA BANIYA,NaN,Closed,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90829,2026-06-01,2026-06-01,UT-R-38912,Ana Wong,Eyebrows,Unique Threading,6/1/2026 10:15 AM,6/1/2026 10:25 AM,0:10,0:10,0:00,Manu Ghimire,NaN,Closed,Add to queue
90830,2026-06-01,2026-06-01,UT-R-38913,Britney Carrasco,Eyebrows,Unique Threading,6/1/2026 10:45 AM,6/1/2026 10:55 AM,0:10,0:10,0:00,Mina Pandey,NaN,Closed,Add to queue
90831,2026-06-01,2026-06-01,UT-R-38919,Melissa Rojas,Nose outside,Unique Threading,6/1/2026 02:35 PM,6/1/2026 02:40 PM,0:05,0:05,0:00,KOPILA BANIYA,NaN,Closed,Add to queue
90832,2026-06-01,2026-06-01,UT-R-38919,Melissa Rojas,Eyebrows,Unique Threading,6/1/2026 02:20 PM,6/1/2026 02:30 PM,0:10,0:10,0:00,KOPILA BANIYA,NaN,Closed,Add to queue
90833,2026-06-01,2026-06-01,UT-R-38922,Katy Brooks,Eyebrows,Unique Threading,6/1/2026 03:15 PM,6/1/2026 03:25 PM,0:10,0:10,0:00,Mina Pandey,NaN,Closed,Add to queue

In [4]:
visits = df.drop_duplicates(subset=["Guest Name", "Appointment Date"])
visits["Appointment Date"] = pd.to_datetime(visits["Appointment Date"])
visits['Gap'] = visits.groupby("Guest Name")["Appointment Date"].diff()
visits["Gap"] = visits["Gap"].dt.days
visits

/var/folders/qj/7k8sr3sd5x52hcn99cf_c4dc0000gn/T/ipykernel_2173/2062163632.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  visits["Appointment Date"] = pd.to_datetime(visits["Appointment Date"])
/var/folders/qj/7k8sr3sd5x52hcn99cf_c4dc0000gn/T/ipykernel_2173/2062163632.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  visits['Gap'] = visits.groupby("Guest Name")["Appointment Date"].diff()
/var/folders/qj/7k8sr3sd5x52hcn99cf_c4dc0000gn/T/ipykernel_2173/2062163632.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  visits["Gap"] = visits["Gap"].dt.days

,Appointment Date,Booked Date,Invoice No,Guest Name,Service Name,Center Name,Start Time,End Time,Scheduled Service Duration,Scheduled Service and Recovery Duration,Recovery Time,Stylist,Room,Status,Queue appointment type,Gap
0,2021-04-02,2021-04-01,II52134753,Lilia Hernandez,upper lip,Unique Threading,4/2/2021 01:08 PM,4/2/2021 01:08 PM,0:00,0:00,0:00,GANGA GIRI,NaN,Closed,NaN,NaN
1,2021-04-02,2021-04-01,II52134773,Chrysta Brake,Eyebrows,Unique Threading,4/2/2021 05:46 PM,4/2/2021 05:46 PM,0:00,0:00,0:00,KOPILA BANIYA,NaN,Closed,NaN,NaN
2,2021-04-02,2021-04-01,II52134756,Tara Chatha,Eyebrows,Unique Threading,4/2/2021 12:51 PM,4/2/2021 12:51 PM,0:00,0:00,0:00,KOPILA BANIYA,NaN,Closed,NaN,NaN
3,2021-04-02,2021-04-01,II52134747,Earlean Dobson,Brazilian Wax,Unique Threading,4/2/2021 12:02 PM,4/2/2021 12:02 PM,0:00,0:00,0:00,GANGA GIRI,NaN,Closed,NaN,NaN
4,2021-04-02,2021-04-01,II52134745,Cavanna Liggens,Eyebrows,Unique Threading,4/2/2021 11:35 AM,4/2/2021 11:35 AM,0:00,0:00,0:00,KOPILA BANIYA,NaN,Closed,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90824,2026-06-01,2026-06-01,UT-R-38917,Shiny Joy,Full Face,Unique Threading,6/1/2026 01:30 PM,6/1/2026 02:00 PM,0:30,0:30,0:00,Manu Ghimire,NaN,Closed,Add to queue,20.0
90827,2026-06-01,2026-06-01,UT-R-38916,Jennifer .,Eyebrows,Unique Threading,6/1/2026 01:00 PM,6/1/2026 01:10 PM,0:10,0:10,0:00,Mina Pandey,NaN,Closed,Add to queue,124.0
90828,2026-06-01,2026-06-01,UT-R-38915,Octavia Madison,Eyebrows,Unique Threading,6/1/2026 12:45 PM,6/1/2026 12:55 PM,0:10,0:10,0:00,Manu Ghimire,NaN,Closed,Add to queue,80.0
90829,2026-06-01,2026-06-01,UT-R-38912,Ana Wong,Eyebrows,Unique Threading,6/1/2026 10:15 AM,6/1/2026 10:25 AM,0:10,0:10,0:00,Manu Ghimire,NaN,Closed,Add to queue,19.0
90830,2026-06-01,2026-06-01,UT-R-38913,Britney Carrasco,Eyebrows,Unique Threading,6/1/2026 10:45 AM,6/1/2026 10:55 AM,0:10,0:10,0:00,Mina Pandey,NaN,Closed,Add to queue,52.0

In [5]:
guest_summary = visits.groupby("Guest Name").agg(
    AverageGap = ('Gap', "mean"),
    LastVisit = ("Appointment Date", "max"),
    VisitCount = ("Appointment Date", "count")
)

guest_summary['DaysSinceLastVisit'] = pd.Timestamp("today") - guest_summary['LastVisit']
guest_summary["DaysSinceLastVisit"] = guest_summary["DaysSinceLastVisit"].dt.days
guest_summary

              AverageGap  LastVisit  VisitCount  DaysSinceLastVisit
Guest Name
4490 .               NaN 2023-10-11           1                 966
5025 .               NaN 2023-10-03           1                 974
6229 .               NaN 2026-03-13           1                  82
A B            29.000000 2026-02-05           2                 118
A S                  NaN 2025-02-27           1                 461
...                  ...        ...         ...                 ...
Zoey Cross    193.111111 2026-04-26          10                  38
Zoey Johnson   27.000000 2021-05-07           2                1853
Zoey Zile      98.333333 2025-08-07           7                 300
Zohra Kazemi  587.500000 2026-05-24           3                  10
Zynae Moore          NaN 2025-08-01           1                 306

[7989 rows x 4 columns]

In [6]:
CHURN_CEILING = 180  # days — gone longer than this = Churned, no matter their personal cycle

def classify(row):
    # Absolute ceiling: gone too long to be worth chasing
    if row["DaysSinceLastVisit"] >= CHURN_CEILING:
        return "Churned"

    if row["VisitCount"] == 1:
        if row["DaysSinceLastVisit"] < 60:
            return "Active"
        elif 60 <= row["DaysSinceLastVisit"] < 120:
            return "At Risk"
        else:
            return "Churned"
    else:
        if row["DaysSinceLastVisit"] < row["AverageGap"]:
            return "Active"
        elif row["AverageGap"] <= row["DaysSinceLastVisit"] < 2 * row["AverageGap"]:
            return "At Risk"
        else:
            return "Churned"

guest_summary["Status"] = guest_summary.apply(classify, axis=1)
print(guest_summary["Status"].value_counts())
guest_summary

Status
Churned    5976
Active     1595
At Risk     418
Name: count, dtype: int64

              AverageGap  LastVisit  VisitCount  DaysSinceLastVisit   Status
Guest Name
4490 .               NaN 2023-10-11           1                 966  Churned
5025 .               NaN 2023-10-03           1                 974  Churned
6229 .               NaN 2026-03-13           1                  82  At Risk
A B            29.000000 2026-02-05           2                 118  Churned
A S                  NaN 2025-02-27           1                 461  Churned
...                  ...        ...         ...                 ...      ...
Zoey Cross    193.111111 2026-04-26          10                  38   Active
Zoey Johnson   27.000000 2021-05-07           2                1853  Churned
Zoey Zile      98.333333 2025-08-07           7                 300  Churned
Zohra Kazemi  587.500000 2026-05-24           3                  10   Active
Zynae Moore          NaN 2025-08-01           1                 306  Churned

[7989 rows x 5 columns]

In [7]:
# Make sure dates are datetime
df["Appointment Date"] = pd.to_datetime(df["Appointment Date"])

# Drop enrichment columns if they exist (so this cell can be re-run safely)
guest_summary = guest_summary.drop(
    columns=["LastService", "LastStylist", "PreferredStylist"], errors="ignore"
)

# Last service they got (most recent appointment)
last_service = (df.sort_values("Appointment Date")
                  .groupby("Guest Name")["Service Name"]
                  .last()
                  .reset_index())
last_service.columns = ["Guest Name", "LastService"]

# Most visited stylist (their "main" stylist by visit count)
preferred_stylist = (df.groupby("Guest Name")["Stylist"]
                       .agg(lambda x: x.value_counts().idxmax())
                       .reset_index())
preferred_stylist.columns = ["Guest Name", "PreferredStylist"]

# Make sure Guest Name is the index before joining
if "Guest Name" in guest_summary.columns:
    guest_summary = guest_summary.set_index("Guest Name")

# Join both on
guest_summary = guest_summary.join(last_service.set_index("Guest Name"))
guest_summary = guest_summary.join(preferred_stylist.set_index("Guest Name"))

# Save for the app
guest_summary.to_csv("guest_summary.csv")

guest_summary.head()

,AverageGap,LastVisit,VisitCount,DaysSinceLastVisit,Status,LastService,PreferredStylist
Guest Name,,,,,,,
4490 .,NaN,2023-10-11,1,966,Churned,Eyebrows,KOPILA BANIYA
5025 .,NaN,2023-10-03,1,974,Churned,Underarms,KOPILA BANIYA
6229 .,NaN,2026-03-13,1,82,At Risk,Chin,KOPILA BANIYA
A B,29.0,2026-02-05,2,118,Churned,Full Face,Mina Pandey
A S,NaN,2025-02-27,1,461,Churned,upper lip,KOPILA BANIYA